import type { Metadata } from "next";
import Branding from "@/components/branding";
import Body from "@/components/body";
import { RootLayoutProps } from "@/types";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(props: Readonly<RootLayoutProps>) {
  return (
    <>
      <Branding />
      <html lang="en">
        <Body {...props} />
      </html>
    </>
  );
}
