import type { Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";
import Branding from "@/components/Branding";
import Body from "@/components/Body";
import { RootLayoutProps } from "@/types";
import "../globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(props: Readonly<RootLayoutProps>) {
  return (
    <>
      <Branding />
      <html lang="en">
        <NextIntlClientProvider>
          <Body {...props} />
        </NextIntlClientProvider>
      </html>
    </>
  );
}
